# This is a basic workflow to help you get started with Actions

name: publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3
        with:
          token: ${{secrets.IAM_GITHUB_BOT_TOKEN}}
        if: github.repository == 'ShanikaWickramasinghe/UniqueMethodNames'

      - name: Checkout
        uses: actions/checkout@v2.3.3
        if: github.repository != 'ShanikaWickramasinghe/UniqueMethodNames'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: Build
        run: |
          npm ci
          npm run build --if-present
      - name: Bump version
        run: |
          git config --global user.email "version.bump@github.action.com"
          git config --global user.name "iam-github-bot"
          npm version patch -m "[WSO2 Release] [GitHub Actions] [Release %s] prepare release %s"
          git push --follow-tags
        if: github.repository == 'ShanikaWickramasinghe/UniqueMethodNames'
